version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run -h 0.0.0.0 -p 8000
    ports:
      - 8001:8000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://flaskapi_test:flaskapi_test@db:5432/flaskapi_test
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=flaskapi_test
      - POSTGRES_PASSWORD=flaskapi_test
      - POSTGRES_DB=flaskapi_test

volumes:
  postgres_data: